# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('lorapso', ['mobility', 'lorawan'])
    module.source = [
        'model/pso-manager.cc',
        'model/particle.cc',
        'model/direction-estimator.cc',
        ]

    module_test = bld.create_ns3_module_test_library('lorapso')
    module_test.source = [
        #'test/loravsf-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'lorapso'
    headers.source = [
        'model/pso-manager.h',
        'model/particle.h',
        'model/direction-estimator.h',
        ]

    # if bld.env.ENABLE_EXAMPLES:
    #     bld.recurse('examples')

    # bld.ns3_python_bindings()

